{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 198,
   "id": "moderate-assignment",
   "metadata": {},
   "outputs": [],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "import decimal as D"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 199,
   "id": "packed-serum",
   "metadata": {},
   "outputs": [],
   "source": [
    "df = pd.read_csv(\"2021-02-06-SettlementNotice - Visa VSS 910.csv\", sep=\";\", parse_dates=[\"ReportDate\"],  thousands=\".\", decimal=\",\", usecols=[\"ReportDate\", \"BusinessTransactionCycle\", \"GrossAmount\"], dtype={\"GrossAmount\": np.float64})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 200,
   "id": "protecting-discretion",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[\"ReportDate\"] = pd.to_datetime(df[\"ReportDate\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 201,
   "id": "engaging-angola",
   "metadata": {},
   "outputs": [],
   "source": [
    "df[\"BusinessTransactionCycle\"] = df[\"BusinessTransactionCycle\"].astype(\"str\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 202,
   "id": "aware-pulse",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>confirmedDate</th>\n",
       "      <th>eventType</th>\n",
       "      <th>amountInBRL</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>0</th>\n",
       "      <td>2021-02-05</td>\n",
       "      <td>The transaction does not have a cycle.</td>\n",
       "      <td>4.338500e+02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>1</th>\n",
       "      <td>2021-02-05</td>\n",
       "      <td>The transaction does not have a cycle.</td>\n",
       "      <td>5.138170e+03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>2</th>\n",
       "      <td>2021-02-05</td>\n",
       "      <td>Dispute Financial</td>\n",
       "      <td>7.479000e+01</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>3</th>\n",
       "      <td>2021-02-05</td>\n",
       "      <td>Originals</td>\n",
       "      <td>7.109171e+04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>4</th>\n",
       "      <td>2021-02-05</td>\n",
       "      <td>Originals</td>\n",
       "      <td>1.776864e+06</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>5</th>\n",
       "      <td>2021-02-05</td>\n",
       "      <td>Dispute Financial</td>\n",
       "      <td>5.050209e+05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>6</th>\n",
       "      <td>2021-02-05</td>\n",
       "      <td>Dispute Response Financial</td>\n",
       "      <td>1.686062e+04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>7</th>\n",
       "      <td>2021-02-05</td>\n",
       "      <td>Not Defined</td>\n",
       "      <td>3.204443e+04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>8</th>\n",
       "      <td>2021-02-05</td>\n",
       "      <td>Originals</td>\n",
       "      <td>8.404387e+07</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>9</th>\n",
       "      <td>2021-02-05</td>\n",
       "      <td>Originals</td>\n",
       "      <td>1.143416e+08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>10</th>\n",
       "      <td>2021-02-06</td>\n",
       "      <td>The transaction does not have a cycle.</td>\n",
       "      <td>1.570000e+03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>11</th>\n",
       "      <td>2021-02-06</td>\n",
       "      <td>The transaction does not have a cycle.</td>\n",
       "      <td>4.900000e+03</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>12</th>\n",
       "      <td>2021-02-06</td>\n",
       "      <td>The transaction does not have a cycle.</td>\n",
       "      <td>3.812000e+02</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>13</th>\n",
       "      <td>2021-02-06</td>\n",
       "      <td>Originals</td>\n",
       "      <td>8.348275e+04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>14</th>\n",
       "      <td>2021-02-06</td>\n",
       "      <td>Originals</td>\n",
       "      <td>1.832042e+06</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>15</th>\n",
       "      <td>2021-02-06</td>\n",
       "      <td>Dispute Financial</td>\n",
       "      <td>4.963857e+05</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>16</th>\n",
       "      <td>2021-02-06</td>\n",
       "      <td>Dispute Response Financial</td>\n",
       "      <td>2.721989e+04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>2021-02-06</td>\n",
       "      <td>Not Defined</td>\n",
       "      <td>1.991870e+04</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>18</th>\n",
       "      <td>2021-02-06</td>\n",
       "      <td>Originals</td>\n",
       "      <td>1.063881e+08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>19</th>\n",
       "      <td>2021-02-06</td>\n",
       "      <td>Originals</td>\n",
       "      <td>1.171828e+08</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "</div>"
      ],
      "text/plain": [
       "   confirmedDate                               eventType   amountInBRL\n",
       "0     2021-02-05  The transaction does not have a cycle.  4.338500e+02\n",
       "1     2021-02-05  The transaction does not have a cycle.  5.138170e+03\n",
       "2     2021-02-05                       Dispute Financial  7.479000e+01\n",
       "3     2021-02-05                               Originals  7.109171e+04\n",
       "4     2021-02-05                               Originals  1.776864e+06\n",
       "5     2021-02-05                       Dispute Financial  5.050209e+05\n",
       "6     2021-02-05              Dispute Response Financial  1.686062e+04\n",
       "7     2021-02-05                             Not Defined  3.204443e+04\n",
       "8     2021-02-05                               Originals  8.404387e+07\n",
       "9     2021-02-05                               Originals  1.143416e+08\n",
       "10    2021-02-06  The transaction does not have a cycle.  1.570000e+03\n",
       "11    2021-02-06  The transaction does not have a cycle.  4.900000e+03\n",
       "12    2021-02-06  The transaction does not have a cycle.  3.812000e+02\n",
       "13    2021-02-06                               Originals  8.348275e+04\n",
       "14    2021-02-06                               Originals  1.832042e+06\n",
       "15    2021-02-06                       Dispute Financial  4.963857e+05\n",
       "16    2021-02-06              Dispute Response Financial  2.721989e+04\n",
       "17    2021-02-06                             Not Defined  1.991870e+04\n",
       "18    2021-02-06                               Originals  1.063881e+08\n",
       "19    2021-02-06                               Originals  1.171828e+08"
      ]
     },
     "execution_count": 202,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df.rename(columns={\"ReportDate\": \"confirmedDate\",\n",
    "                  \"BusinessTransactionCycle\": \"eventType\",\n",
    "                  \"GrossAmount\": \"amountInBRL\"})"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 203,
   "id": "environmental-latter",
   "metadata": {},
   "outputs": [
    {
     "data": {
      "text/plain": [
       "0     The transaction does not have a cycle.\n",
       "1     The transaction does not have a cycle.\n",
       "2                                 chargeback\n",
       "3                                  Originals\n",
       "4                                  Originals\n",
       "5                                 chargeback\n",
       "6                          secondPresentment\n",
       "7                                Not Defined\n",
       "8                                  Originals\n",
       "9                                  Originals\n",
       "10    The transaction does not have a cycle.\n",
       "11    The transaction does not have a cycle.\n",
       "12    The transaction does not have a cycle.\n",
       "13                                 Originals\n",
       "14                                 Originals\n",
       "15                                chargeback\n",
       "16                         secondPresentment\n",
       "17                               Not Defined\n",
       "18                                 Originals\n",
       "19                                 Originals\n",
       "Name: BusinessTransactionCycle, dtype: object"
      ]
     },
     "execution_count": 203,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df[\"BusinessTransactionCycle\"].replace({\"Dispute Financial\": \"chargeback\",\"Dispute Response Financial\": \"secondPresentment\" })"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "connected-pasta",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "supreme-belarus",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.1"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
